# configuration file for Travis CI
# 2016-2017, Sander and Coert Vonk

language: generic
env:
  global:
    - IDE_VERSION=1.8.5
    - SKETCH="ir-interface" 
  matrix:
#   - BOARD="Intel:arc32:arduino_101"
#   - BOARD="arduino:avr:uno"
    - BOARD="esp8266:esp8266:huzzah:FlashSize=4M3M,CpuFrequency=80"

matrix:
  allow_failures:
    - env: BOARD="esp8266:esp8266:huzzah"

before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide  
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json,http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - wget http://downloads.arduino.cc/libraries/library_index.json -O $HOME/.arduino15/library_index.json
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --install-boards esp8266:esp8266;
    fi
  - if [[ "$BOARD" =~ "Intel:arc32:" ]]; then
      arduino --install-boards Intel:arc32;
    fi
  - findAndReplace() { sed -i'' -e"s|$1|$2|g" "$3"; }
  - buildExampleSketch() { 
      EXAMPLE_SKETCH=$PWD/examples/$1/$1.ino;
      if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
        findAndReplace WiFi101 ESP8266WiFi $EXAMPLE_SKETCH;
        findAndReplace WiFiSSLClient WiFiClientSecure $EXAMPLE_SKETCH;
      fi;
      cat $EXAMPLE_SKETCH;
      arduino --verbose-build --verify --board $BOARD $EXAMPLE_SKETCH; 
    }
  - buildSketch() { 
        echo $PWD/$1/$1.ino
        ls $PWD/$1
        arduino --verbose-build --verify --board $BOARD $PWD/$1/$1.ino; 
    }

install:
  - arduino --install-library "WiFiManager"
  - arduino --install-library "IRremoteESP8266"
#  - arduino --install-library "Adafruit GFX Library"
#  - git clone https://github.com/cvonk/esp8266-WiFiClientSecureRedirect.git $HOME/Arduino/libraries/esp8266-WiFiClientSecureRedirect
  - mkdir -p $HOME/Arduino/libraries/
  - ln -s $PWD $HOME/Arduino/libraries/.
  - git clone https://github.com/cvonk/esp8266-framework.git
  - git clone https://github.com/cvonk/esp8266-fatal.git
  - ls -a

script:
   - buildSketch $SKETCH
#  - buildExampleSketch ${SKETCH}

notifications:
  email:
    on_success: change
    on_failure: change
